### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by hopewise** [interactive-pioneers/docker-ruby#7]
if I run the image, I get this error

```
docker run ruby2.2.2
*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 346, in <module>
    main(args)
  File "/sbin/my_init", line 264, in main
    import_envvars(False, False)
  File "/sbin/my_init", line 65, in import_envvars
    for envfile in listdir("/etc/container_environment"):
  File "/sbin/my_init", line 51, in listdir
    return sorted(os.listdir(path))
PermissionError: [Errno 13] Permission denied: '/etc/container_environment'

```

**Comment by ain** [comment]
Thanks for the ticket @hopewise. 

Please run your system from the location that the user running Docker has privileges to. `/etc/container_environment` is clearly a location a normal user account would have as read-only.

**Comment by hopewise** [comment]
So, do you think $ sudo docker run ruby2.2.2 will solve the problem?

**Comment by ain** [comment]
No. I'm suggesting that you should have your user rights seamlessly working. This is not so much of a problem of this particular image than your setup. 

See also [Docker docu regarding non-root access](https://docs.docker.com/engine/installation/linux/debian/#giving-non-root-access).

**Comment by hopewise** [comment]
Thank you, I will look into it

On Thu, Apr 21, 2016 at 11:23 AM, Ain Tohvri notifications@github.com
wrote:

> No. I'm suggesting that you should have your user rights seamlessly
> working. This is not so much of a problem of this particular image than
> your setup.
> 
> See also Docker docu regarding non-root access
> https://docs.docker.com/engine/installation/linux/debian/#giving-non-root-access
> .
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/interactive-pioneers/docker-ruby/issues/7#issuecomment-212802925

## 

## 

## Kind Regards,

Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East

**Comment by ain** [comment]
Closing the ticket. If you shall have any further problems, please feel free to comment below.
